/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#![allow(non_camel_case_types,non_upper_case_globals,unused_imports,unused_variables,unused_assignments,unused_mut)]


pub mod DOMExceptionBinding {
#![allow(non_camel_case_types,non_upper_case_globals,unused_imports,unused_variables,unused_assignments,unused_mut)]


} // mod DOMExceptionBinding

use dom::bindings::str::DOMString;

pub trait DOMExceptionMethods {
    fn Code(&self) -> u16;
    fn Name(&self) -> DOMString;
    fn Message(&self) -> DOMString;
    fn Stringifier(&self) -> DOMString;
}